export const DEFAULT_SERVICE_NAMES = [
  "Private Elementary School Tutoring",
  "Private Middle School Tutoring",
  "Private High School Tutoring",
  "Private Test Prep Tutoring",
  "Semi-private Elementary School Tutoring",
  "Semi-private Middle School Tutoring",
  "Semi-private High School Tutoring",
  "Semi-private Test Prep Tutoring",
  "Group Elementary School Classes",
  "Group Middle School Classes",
  "Group High School Classes",
  "Group Test Prep Classes",
  "Elementary School Workshops",
  "Middle School Workshops",
  "High School Workshops",
  "Test Prep Workshops",
  "Elementary School Camps",
  "Middle School Camps",
  "High School Camps",
  "Test Prep Camps",
  "Free Workshops",
  "Assessments",
  "Free/Comped Private Tutoring Sessions",
];

export const DEFAULT_SUBJECTS: { subject_name: string; topics: string[] }[] = [
  {
    subject_name: "Math",
    topics: [
      "Arithmetic (add, subtract, multiply, divide)",
      "Pre-Algebra",
      "Algebra I",
      "Algebra II",
      "Geometry",
      "Trigonometry",
      "Pre-Calculus",
      "Calculus (limits, derivatives, integrals)",
      "Statistics",
      "Probability",
      "SAT / ACT Math",
      "Common Core Math",
    ],
  },
  {
    subject_name: "Reading & Language Arts",
    topics: [
      "Reading (phonics, comprehension, fluency)",
      "Writing (grammar, sentence structure, essays)",
      "Spelling",
      "Vocabulary",
      "Literature",
      "ESL Reading/Writing",
    ],
  },
  {
    subject_name: "Science",
    topics: [
      "General Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Earth Science",
      "Environmental Science",
      "Anatomy & Physiology",
      "AP Science",
    ],
  },
  {
    subject_name: "Social Studies",
    topics: ["U.S. History", "World History", "Geography", "Civics / Government", "Economics", "AP History"],
  },
  {
    subject_name: "Test Prep",
    topics: ["SAT", "ACT", "PSAT", "ISEE", "SSAT", "SHSAT", "Regents Exams", "State Assessments", "AP Exams"],
  },
  {
    subject_name: "College & Career Prep",
    topics: [
      "College Essays",
      "College Applications",
      "Study Skills",
      "Note-Taking",
      "Test Anxiety",
      "Career Readiness",
    ],
  },
  {
    subject_name: "Foreign Languages",
    topics: [
      "Spanish",
      "French",
      "Italian",
      "German",
      "Mandarin",
      "Cantonese",
      "Japanese",
      "Korean",
      "Arabic",
      "Hebrew",
      "Portuguese",
    ],
  },
  { subject_name: "ESL / ELL", topics: ["Speaking", "Reading", "Writing", "Grammar", "Conversation"] },
  {
    subject_name: "Special Education & Academic Support",
    topics: [
      "Special Education",
      "IEP Support",
      "504 Support",
      "Learning Differences",
      "ADHD Support",
      "Executive Functioning",
      "Organization & Time Management",
    ],
  },
  {
    subject_name: "Computer & Technology",
    topics: [
      "Computer Basics",
      "Microsoft Word / Excel / PowerPoint",
      "Google Workspace",
      "Coding (Python, JavaScript, Java, Scratch)",
      "Web Development",
      "Data Analysis",
      "Computer Science (K–12)",
    ],
  },
  {
    subject_name: "Business & Finance",
    topics: ["Accounting", "Economics", "Personal Finance", "Entrepreneurship", "Excel for Business"],
  },
  {
    subject_name: "Arts & Music",
    topics: ["Art (drawing, painting)", "Music (piano, guitar, violin, voice)", "Music Theory", "Drama / Theater"],
  },
  {
    subject_name: "Early Childhood / Elementary",
    topics: ["Kindergarten Readiness", "Early Literacy", "Early Math", "General Homework Help"],
  },
];
